In [1]:
import numpy as np


In [5]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a= np.ones((50,1))+49
a

array([[50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.]])

In [22]:
a= np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
a= np.arange(3)
a


array([0, 1, 2])

In [27]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a[1,2]

6

In [32]:
a= np.arange(1,5,1)
a

array([1, 2, 3, 4])

In [36]:
a[0:3]

array([1, 2, 3])

In [39]:
a= np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
a[1,:]

array([5, 6, 7, 8])

In [41]:
a[:,1]

array([2, 6])

In [42]:
a[1,2]

7

In [44]:
a[:,1:3]

array([[2, 3],
       [6, 7]])

In [48]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [50]:
sum= np.sum(a)
sum

6

In [52]:
sum= a.sum()
sum


6

In [53]:
a= np.array([[1,1,1],[2,2,2],[3,3,3]])
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [55]:
print(np.sum(a,1))

[3 6 9]


In [56]:
a= np.array([[80,90,60],[50,70,95],[85,85,95]])

In [63]:
mean= np.mean(a,1)
mean

array([76.66666667, 71.66666667, 88.33333333])

In [65]:
mean= np.mean(a[1:,0])
mean

67.5

In [66]:
max= np.max(a[:,1])
max

90

In [67]:
std= np.std(a,0)
std


array([15.45603083,  8.49836586, 16.49915823])

In [69]:
low= np.min(std)
low

8.498365855987975

In [6]:
import numpy as np
arr1= [[1,2],[3,4]]
arr2= [[5,6],[7,8]]
a= np.array(arr1)
b= np.array(arr2)
print(a*b)

[[ 5 12]
 [21 32]]


In [7]:
print(a+2)

[[3 4]
 [5 6]]


In [8]:
print(a**2)

[[ 1  4]
 [ 9 16]]


In [10]:
a= np.arange(1,10)
b= np.ones(9)*2
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [11]:
 print(a*b)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [12]:
for loc in np.arange(0,9):
    print(a[loc]*b[loc])


2.0
4.0
6.0
8.0
10.0
12.0
14.0
16.0
18.0


In [13]:
a= np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
c=[]
b=[]
for i in range(2,10):
    c= i*a
    b.append(c)

In [15]:
b

[array([ 2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 3,  6,  9, 12, 15, 18, 21, 24, 27]),
 array([ 4,  8, 12, 16, 20, 24, 28, 32, 36]),
 array([ 5, 10, 15, 20, 25, 30, 35, 40, 45]),
 array([ 6, 12, 18, 24, 30, 36, 42, 48, 54]),
 array([ 7, 14, 21, 28, 35, 42, 49, 56, 63]),
 array([ 8, 16, 24, 32, 40, 48, 56, 64, 72]),
 array([ 9, 18, 27, 36, 45, 54, 63, 72, 81])]

In [27]:
a= np.arange(2,10)
b= np.arange(1,10)
b.shape

(9,)

In [24]:
a= np.tile(a,(9,1))

a.shape

(9, 8)

In [28]:
c= b.transpose()
c.shape

(9,)

In [30]:
a=np.arange(2,10)
b=np.arange(1,10)
a=np.tile(a,(9,1)) 
a=np.transpose(a)
b=np.tile(b,(8,1))
a*b


array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [39]:
a=np.arange(2,10)
b=np.arange(1,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a=np.tile(a,(9,1)) 
a

array([[2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
a=np.transpose(a)
a

array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [42]:
b=np.tile(b,(8,1))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
inputLayer = np.array([0.2,0.5,1])
weightLayer = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]])


In [45]:
answer= np.dot(inputLayer,weightLayer)

In [46]:
answer

array([0.92, 1.09, 1.26])

In [47]:
v= np.tile(inputLayer, (3,1))
v

array([[0.2, 0.5, 1. ],
       [0.2, 0.5, 1. ],
       [0.2, 0.5, 1. ]])

In [49]:
n= np.transpose(weightLayer)
n

array([[0.1, 0.4, 0.7],
       [0.2, 0.5, 0.8],
       [0.3, 0.6, 0.9]])

In [50]:
mult= n*v
mult

array([[0.02, 0.2 , 0.7 ],
       [0.04, 0.25, 0.8 ],
       [0.06, 0.3 , 0.9 ]])

In [51]:
dot= np.sum(mult,1)

In [52]:
dot

array([0.92, 1.09, 1.26])

In [53]:
 import re
    

In [56]:
Text= 'my number is 010-1234-5678 and your number is 010-9876-5432'


In [65]:
data= re.findall('\d{3}-\d{4}-\d{4}', Text)

In [66]:
data

['010-1234-5678', '010-9876-5432']

In [114]:
text= '999 1st Avenue, Bigtown, NY, 11222.00. igh Street, Any City, MI 48034.234.55'



In [115]:
data= re.findall('\d{5}.\d+.\d',text)
data

['48034.234.5']

In [77]:
text= '754921-2512512 754921-151251 754921-4512512 754921-5512512'
data= re.findall('\d{4}-[2,4]\d*',text)
data

['4921-2512512', '4921-4512512']

In [116]:
text= 'Send personal email  to ben@forta.com. For questions about a book use  support@forta.com. Feel free to send unsolicited email to spam@forta.ac.kr(wouldn’t it be nice if it were that simple, huh?).'
email= re.findall('\w+@\w+.\w+.\w+',text)
email


['ben@forta.com', 'support@forta.com', 'spam@forta.ac.kr']

In [124]:
text = """park 850201-1234567 kim 900403-2418556 lee 891231-1445154"""
result = re.sub(r'(\d{6})(-)(\d)(\d{6})',"\\1>\\2\\4", text)
result


'park 850201>-234567 kim 900403>-418556 lee 891231>-445154'